name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Backend Docker image
      run: cd first-backend && docker build . --file Dockerfile --tag code-bootcamp-first-backend:$(date +%s)
